Improve skipped question's behavior
enquirer/prompt-list pull request #4
Opened 2017-10-26 04:38 UTC by albizures

override "when" function to avoid setting a value when there is not a default value and the question was not asked.

resolve #3

2017-10-26 18:02 UTC, doowb requested changes
Thanks @albizures!

I have a few comments below based on some of the features that are in `prompt-base` that aren't obvious by looking at `prompt-list` code.

2017-10-26 18:02 UTC, doowb commented on index.js
> +  this.default = question.default;
This isn't necessary, the `default` value is on `this.options.default`

2017-10-26 18:02 UTC, doowb commented on index.js
> +  this._when = question.when;
This isn't necessary, you can use `Radio.prototype.when` below.

2017-10-26 18:02 UTC, doowb commented on index.js
> +  if (this._when && !this._when.apply(this, arguments)) {
It's possible for `this.when` to return a promise, so the results need to be resolved first:

```js
return Promise.resolve(Radio.prototype.when.apply(this, arguments))
  .then(function(when) {
    ...
    return when;
  });
```

2017-10-26 18:02 UTC, doowb commented on index.js
> +    this.position = this.default === undefined ? -1 : this.default;
To get the correct position, use `this.choices.getIndex(this.options.default)`

2017-10-26 18:04 UTC, doowb commented
Thanks for the PR @albizures! I requested some changes based on conveniences that are already built into `prompt-list` via `prompt-base` and `prompt-choices`.

Also, thanks for linting.

2017-10-27 01:35 UTC, albizures commented
hey @doowb, I resolved all of your comments 😃 

Thanks

2017-12-26 17:11 UTC, doowb approved these changes

2017-12-26 17:13 UTC, doowb commented
@albizures thanks for making the changes and for the PR! Sorry for the delay in getting back to this.

2017-12-26 17:13 UTC, merged